### ISSUE TITLE
Zephyr Daemon Not Syncing

### ISSUE THREAD

**Issue by angeletti01** [ZephyrProtocol/zephyr#24]
I have executed zephyrd.exe for the first time and the daemon is unable to connect with the server. 

![Daemon not connecting to server](https://github.com/ZephyrProtocol/zephyr/assets/79180157/8f8e456a-a18d-46ee-b2eb-8553a168eb20)

**Comment by ZephyrProtocol** [comment]
Seed nodes were likely down at this time, will work now with latest build, thanks!

Best to join discord for support, not open github issues.
Find our discord link on our website: https://www.zephyrprotocol.com/
Or directly: https://discord.gg/y4mzbDYSqQ
