### ISSUE TITLE
get_tx_key error

### ISSUE THREAD

**Issue by scars1** [ZephyrProtocol/zephyr#26]
[wallet ZEPHYR2S4]: get_tx_key b817d6f207c449b4b8bc4328291ea0725221f5008b6038b1c8b5fb48fb3e1e68
Wallet password:
Error: no tx keys found for this txid

Any tx id all same result,so how to solve it?

**Comment by fennzar** [comment]
The tx key for a transaction is saved to your wallet cache file.
If you restore your wallet that information would be lost. The error just says its not found, meaning its not in the cache file.

If you sent this tx with the wallet gui then more than likely that info is simply not being saved to the wallet cache file
