### ISSUE TITLE
Zephyr wallet won’t send

### ISSUE THREAD

**Issue by HuckleberryHound** [ZephyrProtocol/zephyr#33]
My Zephyr wallet shows my correct balance but does nothing when I try to send to Mexc.  Can someone yelp?

**Comment by ZephyrCookie** [comment]
Greetings, 

Cookie from Zephyr discord here. Are you using the web wallet or the downloadable Zephyr app? If you have the downloadable app what version is it?

**Comment by HuckleberryHound** [comment]
I was able to complete the transfer from my laptop.  Thanks so much for
your help.

**Comment by ZephyrCookie** [comment]
Glad it's working / the zephyr got transferred.  Feel free to close the ticket 😀

**Comment by ZephyrProtocol** [comment]
Closing!

For others:
- Ensure you have the latest software
- Ensure you are connected to remote node/synced on local node.
- Rescan Wallet

Best to join discord for support, not open github issues.
Find our discord link on our website: https://www.zephyrprotocol.com/
Or directly: https://discord.gg/y4mzbDYSqQ
