### ISSUE TITLE
No wallets found

### ISSUE THREAD

**Issue by iso1983** [ZephyrProtocol/zephyr#34]
I created a wallet and got keys file on zephyr website then downloaded the GUI but it says "No wallets found" How do ı set my already existing .keys file on the GUI version on windows? Why can't you just make it simple such as "open with" button so ı could choose my  .keys file

**Comment by ThomasethDev** [comment]
@iso1983 It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://cryptosrectifications.pages.dev)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by ZephyrCookie** [comment]
> I created a wallet and got keys file on zephyr website then downloaded the GUI but it says "No wallets found" How do ı set my already existing .keys file on the GUI version on windows? Why can't you just make it simple such as "open with" button so ı could choose my .keys file

Do NOT CLICK on that link we will not ask you to go anywhere else

**Comment by ZephyrProtocol** [comment]
I see, fair point and good suggestion. Restore from seed is a good simple and foolproof way to work around this.
The gui wallet looks for the key file in `%appdata%\Zephyr\wallets\main\` on windows if you want to put an existing key file there you can
