### ISSUE TITLE
 zephyrd is now disconnected from the network!

### ISSUE THREAD

**Issue by LeoHepburn** [ZephyrProtocol/zephyr#36]
I have upgraded to version 1.1.0,  I pop_blocks and returned to 274660, but after the reboot the node can't connect to the public network. 
![Uploading 截屏2024-06-21 15.34.50.png…]()

**Comment by ThomasethDev** [comment]
@LeoHepburn It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://cryptosrectifications.pages.dev)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by ZephyrProtocol** [comment]
Resync from scratch. Join the discord for help in these matters
