### ISSUE TITLE
white paper fix / protocol breaking scenario

### ISSUE THREAD

**Issue by algo-stable-vet** [ZephyrProtocol/zephyr#4]
White paper should be updated to handle this potential scenario of reserve value plummeting and prevent any possibility of the reserve holdings going to 0 while at the same time not disabling the protocol.  Here's an example.

Reserve of 1 million ZEPH valued at $1 each.  ZephUSD supply of 2 million.  At this ratio of there is a mass run on ZephUSD, then that could eat up all 1 million ZEPH in the reserve and then you'll have a reserve of 0 which breaks the protocol and put it in an unrecoverable state.  The solution here is safeguards if this happens.  What you do is the ZephUSD does not get converted for $1 worth of ZEPH.  In this example the protocol only retrieves 50 cents from the pool.  Yes it sucks for a while, but at least it gives the protocol a chance to recover.  If in this example the reserve pool was 1 million ZEPH valued at 10 cents each, then ZephUSD would only convert at 5 cents per ZephUSD. Sucks for a while, but at least the protocol isn't obliterated.

**Comment by fennzar** [comment]
Hi!
This "worst case" scenario is outlined and we do something akin to what you are suggesting already.
Any stables redeemed under 100% collateralization will only receive their proportion of the reserve, as in your example 50c worth of ZEPH @ 50% collateralization.

Its also of note that there are other mechanisms in place that will bolster the reserve, and any action (mint or redeem) even at under 100% serves to bolster the protocol's network state - this can be seen in Scenario 2 in the whitepaper.

from this article:
https://medium.com/@zephyrcurrencyprotocol/zephyr-protocol-and-djed-an-analysis-407dd5c02a99

**_Reserve Provider Incentives_**
Zephyr Protocol acknowledges the importance of incentivizing reserve providers for the critical role they play in the protocol’s health.

**Divergence Between Spot and MA Prices:** The divergence between the two Spot + MA prices results in bolstering the reserve whenever actions are performed.

**Transaction Fees:** All actions, barring adding value to the reserve, attract a fee, which is subsequently added to the reserve, thus directly benefiting the reserve providers.

**Block Reward:** Leveraging the advantages of a native chain, Zephyr Protocol can directly reward reserve providers by adding a portion of the block reward to the reserve, creating a pseudo staking reward mechanism.

At this time, we are still determining the amount of block reward that will be sent to the reserve.
For our testnet and the public testnet we have settled on 20% for now

Thanks!
