### ISSUE TITLE
INPUT STEAM ERROR LOG IN 

### ISSUE THREAD

**Issue by BBS-CRYPTO** [ZephyrProtocol/zephyr#41]
I've been mining Zephyr for a few months now. Recently I've tried logging into wallet and I'm getting input stream error. Unfortunately, I do not have keys only key file to get into wallet ... is there a way to fix this or I'm I out on mined coin?

![Screenshot (8)](https://github.com/user-attachments/assets/0c350c14-273a-41e0-8d42-c06456d99dc3)

**Comment by Hornung39** [comment]
same issue here

**Comment by fennzar** [comment]
Clearing cache solves this problem, which is why a new browser works.
This was due to the changes from the v1.2.0 update

**Comment by BBS-CRYPTO** [comment]
I've tried clearing cache and new browser no luck doesn't work.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
